# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ironcode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/KSD-CO/IronCode"
  version "1.17.3"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KSD-CO/IronCode/releases/download/v1.17.3/ironcode-darwin-x64.zip"
      sha256 ""

      def install
        bin.install "ironcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KSD-CO/IronCode/releases/download/v1.17.3/ironcode-darwin-arm64.zip"
      sha256 "94f79c8dde24e7f37b7d812cee07b4da28e6aefdf5646392bb6ac438a529afa2"

      def install
        bin.install "ironcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/KSD-CO/IronCode/releases/download/v1.17.3/ironcode-linux-x64.tar.gz"
      sha256 ""
      def install
        bin.install "ironcode"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/KSD-CO/IronCode/releases/download/v1.17.3/ironcode-linux-arm64.tar.gz"
      sha256 ""
      def install
        bin.install "ironcode"
      end
    end
  end
end

