# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ironcode < Formula
  desc "The AI coding agent built for the terminal."
  homepage "https://github.com/KSD-CO/IronCode"
  version "1.5.3"

  depends_on "ripgrep"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KSD-CO/IronCode/releases/download/v1.5.3/ironcode-darwin-x64.zip"
      sha256 ""

      def install
        bin.install "ironcode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KSD-CO/IronCode/releases/download/v1.5.3/ironcode-darwin-arm64.zip"
      sha256 "104efa10e0f037f3848b5fae1b2d37429980bf09f71ffc07b8e0df22f6ffe7e7"

      def install
        bin.install "ironcode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/KSD-CO/IronCode/releases/download/v1.5.3/ironcode-linux-x64.tar.gz"
      sha256 "09aafc86f90ef2ed690801a6c75d30afef9e21532254448207fb345a866fd224"
      def install
        bin.install "ironcode"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/KSD-CO/IronCode/releases/download/v1.5.3/ironcode-linux-arm64.tar.gz"
      sha256 ""
      def install
        bin.install "ironcode"
      end
    end
  end
end

